import type { Metadata } from "next";
import { Ruda, Rubik_Glitch } from "next/font/google";
import "./globals.css";
import { Header } from "../components/layout/header";
import { Footer } from "../components/layout/footer";
import { ReviewProvider } from "../context/selectedReviewContext";

export const rudaFont = Ruda({
  subsets: ["latin"],
});

export const rubikGlitchFont = Rubik_Glitch({
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rudaFont.className}`}>
        <ReviewProvider>
          <Header />
          {children}
          <Footer />
        </ReviewProvider>
      </body>
    </html>
  );
}
